#pragma once

// BVEVENTTYPE_{LISTENER}_EVENT
typedef enum class BVEventType
{
    BVEVENTTYPE_DISCOVERY_REQUEST_START,
    BVEVENTTYPE_DISCOVERY_REQUEST_SHUTDOWN,

    BVEVENTTYPE_APP_PUBLISHED_SERVICE, // published service list or pushed on queue

    BVEVENTTYPE_SERVICE_REQUEST_START,
    BVEVENTTYPE_SERVICE_REQUEST_SHUTDOWN,

    BVEVENTTYPE_TERMINATE_ALL
} BVEventType;