#pragma once
typedef enum class BVEventType
{
    BVEVENTTYPE_DISCOVERY_START,
    BVEVENTTYPE_DISCOVERY_STOP,
    BVEVENTTYPE_DISCOVERY_PUBLISHED_SERVICE,
    BVEVENTTYPE_SERVICE_START,
    BVEVENTTYPE_SERVICE_STOP,





    BVEVENTTYPE_TERMINATE_ALL
} BVEventType;