#pragma once

// BVEVENTTYPE_{LISTENER}_EVENT
typedef enum class BVEventType
{
    BVEVENTTYPE_DISCOVERY_REQUEST_START,
    BVEVENTTYPE_DISCOVERY_REQUEST_PAUSE,
    BVEVENTTYPE_DISCOVERY_REQUEST_RESUME,
    BVEVENTTYPE_DISCOVERY_REQUEST_SHUTDOWN, // terminate all; usually BVEVENTTYPE_TERMINATE_ALL
    BVEVENTTYPE_DISCOVERY_REQUEST_RESTART,

    BVEVENTTYPE_APP_PUBLISHED_SERVICE, // published service list or pushed on queue

    BVEVENTTYPE_SERVICE_REQUEST_START,
    BVEVENTTYPE_SERVICE_REQUEST_SHUTDOWN,

    BVEVENTTYPE_TERMINATE_ALL, // ALL_TERMINATE?

    // Test and Debug events
    BVEVENTTYPE_TEST_ECHO,
    BVEVENTTYPE_TEST_HEARBTEAT

} BVEventType;