@startuml Top-level Architecture View
skinparam componentStyle uml2
left to right direction

' Components
component "Broker" as Broker
component "Discovery" as Discovery
component "App" as App
component "Service" as Service

' Message Topics (Interfaces)
interface "DiscoveryEvents" as DiscoveryEvents
interface "AppEvents" as AppEvents

' Broker provides all topics
Broker -- DiscoveryEvents
Broker -- AppEvents

' Publishers
Discovery ..> DiscoveryEvents : publish
App ..> AppEvents : publish

' Subscribers
App ..> DiscoveryEvents : subscribe
Discovery ..> AppEvents : subscribe

' Notes
note right of Broker
Central message router.
No component communicates directly.
Each subscription means receiving certain
event types.
end note

note bottom of AppEvents
Each event comes as a message
containing event type and data.
end note

note right of Service
Service is not a component, however 
it is used to register the service
and get Service data:
hostname, regtype, domain and port
end note

@enduml
