@startuml Discovery State Diagram

participant DiscoveryMailboxThread    as DiscoveryMbx
participant DiscoveryWorkerThread     as DiscoveryWT
participant Broker                    as Broker
participant App                       as App

loop not isPaused
    DiscoveryWT -> DiscoveryWT : Check isPaused

?-> DiscoveryWT: Poll FD
activate DiscoveryWT
    DiscoveryWT -> DiscoveryWT  : Service found
    DiscoveryWT -> Broker       : //BVEVENTTYPE_APP_PUBLISHED_SERVICE//
deactivate DiscoveryWT
Broker -> App                   : //BVEVENTTYPE_APP_PUBLISHED_SERVICE//
App -> App                      : Update state
    App -> Broker               : //BVEVENTTYPE_DISCOVERY_REQUEST_PAUSE//
    Broker -> DiscoveryMbx      : //BVEVENTTYPE_DISCOVERY_REQUEST_PAUSE//
    DiscoveryMbx -> DiscoveryWT : Pause browsing

else isPaused
    DiscoveryWT -> DiscoveryWT : wait/sleep
    note left
    Discovery implements a way
    to omit polling in a way that
    nothing is read from the daemon.
    end note
    App -> Broker               : //BVEVENTTYPE_DISCOVERY_REQUEST_RESUME//
    Broker -> DiscoveryMbx      : //BVEVENTTYPE_DISCOVERY_REQUEST_RESUME//
    DiscoveryMbx -> DiscoveryWT : Resume browsing 
    DiscoveryWT -> DiscoveryWT  : Go to loop
end

App -> Broker                : //BVEVENTTYPE_TERMINATE_ALL//
Broker -> DiscoveryMbx       : //BVEVENTTYPE_TERMINATE_ALL//
Broker -> Broker             : Return  
DiscoveryMbx -> DiscoveryWT  : Call //::OnShutdown()// 
DiscoveryMbx -> DiscoveryMbx : Return
DiscoveryWT -> DiscoveryWT   : Return
App -> App                   : Return
@enduml